version: '3.8'

services:
  server:
    depends_on:
      - db
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - server/app_env
    ports:
      - "4000:4000"
    volumes:
      - ./server:/app:cached

  client:
    build:
      context: './client'
      dockerfile: Dockerfile
    env_file:
      - client/app_env      
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app:cached

  db:
    image: postgres:14.0
    volumes:
      - db_data:/var/lib/postgresql/data
      - ../../log:/root/log:cached
    environment:
      POSTGRES_DB: server_development
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

volumes:
  db_data:
